### PR TITLE
Fix CMake Options CI for SLANG_LIB_TYPE=STATIC and SLANG_ENABLE_ASAN

### LINKED ISSUE #13068: CMake Options CI broken by vendored spvdb: SLANG_LIB_TYPE=STATIC and SLANG_ENABLE_ASAN builds fail to link
The weekly scheduled **CMake Options** workflow has been failing since the Sep 12 run: [run 34682178730](https://github.com/shader-slang/slang/actions/runs/34682178730) (master @ `4d7939e59`). 18 build jobs fail, plus the `check-cmake` aggregation gate.

The previous run on Sep 5 (`961e4e59e`) was green. All 18 failures fall into exactly two option configurations, and both were introduced by #12896 ("Vendor spvdb and add SPVDB_DEBUGGER regression tests under `tests/debuginfo`", `f94dd4ecc`, merged Sep 9), which links the vendored `spvdb` static library into `slang-test`.

## Failure 1 — `SLANG_LIB_TYPE=STATIC` (10 jobs, all platforms)

`slang-test` fails to link ([linux-debug job](https://github.com/shader-slang/slang/actions/runs/34682178730/job/103522728492)):

```
libspvdb.a(image_sampler.cpp.o): in function `spvdb::load_image(...)':
tests/spvdb/lib/interpreter/image_sampler.cpp:34: undefined reference to `stbi_loadf'
tests/spvdb/lib/interpreter/image_sampler.cpp:41: undefined reference to `stbi_image_free'
```

Three pre-existing decisions collide here:

- `cmake/CompilerFlags.cmake` defines `STB_IMAGE_STATIC` when `SLANG_LIB_TYPE` is `STATIC` (from #6374). That gives every `stbi_*` function internal linkage.
- `tools/slang-test/slang-test-main.cpp` is the single translation unit that compiles `STB_IMAGE_IMPLEMENTATION`.
- `tests/spvdb/CMakeLists.txt` sets `SPVDB_SKIP_STB_IMAGE_IMPL=1` whenever spvdb is built as a subdirectory, on the assumption that the parent provides the symbols.

In a shared build that works. In a static build the parent's `stbi_*` symbols never leave `slang-test-main.cpp`'s translation unit, so spvdb has nothing to link against.

## Failure 2 — `SLANG_ENABLE_ASAN=ON` (8 jobs, Windows only)

```
spvdb.lib(spvdb.obj) : error LNK2038: mismatch detected for 'annotate_string':
  value '0' doesn't match value '1' in cmake_pch.obj [slang-test.vcxproj]
... 12 mismatches; fatal error LNK1319
```

`spvdb` is created with a plain `add_library(spvdb STATIC ...)` rather than through `slang_add_target`, so it never goes through `set_default_compile_options` and never receives `/fsanitize=address`. `slang-test` does. MSVC's ASan changes the ABI of the annotated standard containers (`annotate_string` / `annotate_vector`), so sanitized and unsanitized objects cannot be linked into the same binary.

`check-cmake` is only the aggregation gate ("One or more CMake option builds failed or were cancelled") and has no independent failure.

## Proposed fix

1. **STATIC**: gate `SPVDB_SKIP_STB_IMAGE_IMPL` on whether the parent's `stbi_*` symbols are actually linkable, rather than merely on spvdb being a subdirectory. Slang turns the skip off when `SLANG_LIB_TYPE=STATIC` so spvdb compiles its own copy — safe, since the parent's copies have internal linkage and cannot collide.
2. **ASAN**: extract the sanitizer block of `set_default_compile_options` into a reusable `add_sanitizer_options(target)` and apply it to `spvdb`, so the vendored library keeps its own warning configuration but agrees with `slang-test` about ASan.

Both were verified locally by configuring and building `slang-test` from scratch (VS 2026 / Ninja Multi-Config, Debug): `SLANG_LIB_TYPE=STATIC` and `SLANG_ENABLE_ASAN=ON` both link, and the default shared/non-ASan configuration is unchanged.

### PR DESCRIPTION
**Pull request by jkwak-work**
Fixes #13068

## Motivation

The weekly scheduled **CMake Options** workflow has been failing since the Sep 12 run, [run 34682178730](https://github.com/shader-slang/slang/actions/runs/34682178730) on master `4d7939e59`. 18 build jobs fail, plus the `check-cmake` aggregation gate. The previous run on Sep 5 (`961e4e59e`) was green.

All 18 failures fall into exactly two option configurations, and both were introduced by #12896, which links the vendored `spvdb` static library into `slang-test`.

**`SLANG_LIB_TYPE=STATIC`** fails to link `slang-test` on every platform ([linux-debug job](https://github.com/shader-slang/slang/actions/runs/34682178730/job/103522728492)):

```
libspvdb.a(image_sampler.cpp.o): in function `spvdb::load_image(...)':
tests/spvdb/lib/interpreter/image_sampler.cpp:34: undefined reference to `stbi_loadf'
tests/spvdb/lib/interpreter/image_sampler.cpp:41: undefined reference to `stbi_image_free'
```

**`SLANG_ENABLE_ASAN=ON`** fails to link `slang-test` on Windows:

```
spvdb.lib(spvdb.obj) : error LNK2038: mismatch detected for 'annotate_string':
  value '0' doesn't match value '1' in cmake_pch.obj [slang-test.vcxproj]
... 12 mismatches; fatal error LNK1319
```

`check-cmake` is only the aggregation gate ("One or more CMake option builds failed or were cancelled") and has no independent failure.

## Proposed solution

For the static build, state the condition that actually governs the decision. `tests/spvdb/CMakeLists.txt` suppressed its own copy of the stb_image implementation whenever it was built as a subdirectory, on the assumption that the embedding parent supplies those symbols. That assumption is what broke: the useful question is not "am I a subdirectory?" but "are the parent's `stbi_*` symbols linkable from here?" The gate is now a `SPVDB_PARENT_PROVIDES_STB_IMAGE` variable that the parent sets, defaulting to `TRUE` so standalone and ordinary embedded builds are unchanged.

For ASan, apply the flags at the level that owns them. `spvdb` is a vendored library with its own warning configuration, so it deliberately does not go through `slang_add_target` / `set_default_compile_options` — but sanitizer settings are not per-library taste, they are a whole-binary ABI property. Splitting the sanitizer block out of `set_default_compile_options` into its own `add_sanitizer_options()` lets `spvdb` inherit exactly that one concern and nothing else, keeping a single source of truth for the flags.

## Change summary

| File | Change |
| --- | --- |
| `cmake/CompilerFlags.cmake` | Extract the `SLANG_ENABLE_ASAN` block of `set_default_compile_options` into a new `add_sanitizer_options(target)` function; `set_default_compile_options` now calls it (still honoring `SKIP_ASAN`). Pure move — no flag changes. |
| `tests/spvdb/CMakeLists.txt` | Gate `SPVDB_SKIP_STB_IMAGE_IMPL` on the new `SPVDB_PARENT_PROVIDES_STB_IMAGE` variable, which defaults to `TRUE`. |
| `tools/CMakeLists.txt` | Set `SPVDB_PARENT_PROVIDES_STB_IMAGE` to `FALSE` when `SLANG_LIB_TYPE` is `STATIC`, before `add_subdirectory` of spvdb; call `add_sanitizer_options(spvdb)` after it. |

## Concepts and vocabulary

- **`STB_IMAGE_STATIC`** — an stb_image configuration macro that makes `STBIDEF` expand to `static`, giving every `stbi_*` function internal linkage. Slang defines it for static-library builds (`cmake/CompilerFlags.cmake:233`, added in #6374).
- **`SPVDB_SKIP_STB_IMAGE_IMPL`** — spvdb's own macro, read at `tests/spvdb/lib/interpreter/image_sampler.cpp:5`, that suppresses its `#define STB_IMAGE_IMPLEMENTATION` so an embedding project can own the single copy.
- **MSVC container annotations** — `/fsanitize=address` makes MSVC's STL emit `annotate_string` / `annotate_vector` hooks, which is an ABI change recorded as a linker `DETECTOBJ` directive. Every object in a binary must agree, or the link fails with `LNK2038`.

## Process report

**Why the static build broke.** Three pre-existing, individually reasonable decisions collide. `tools/slang-test/slang-test-main.cpp:40` is the one translation unit that compiles `STB_IMAGE_IMPLEMENTATION`. In a static-library build `cmake/CompilerFlags.cmake:233` also defines `STB_IMAGE_STATIC`, so every `stbi_*` function it generates has internal linkage and is confined to `slang-test-main.cpp`. Meanwhile `tests/spvdb/CMakeLists.txt` defined `SPVDB_SKIP_STB_IMAGE_IMPL=1` for any subdirectory build, so `image_sampler.cpp` skipped its own implementation and emitted external references to `stbi_loadf` and `stbi_image_free`. In a shared build those resolve against `slang-test-main.cpp`'s external-linkage definitions; in a static build there is nothing to resolve against, and `ld` reports exactly the two undefined references above.

**Is the input shape correct, or should the producer be fixed?** The shape in question is "parent compiles the stb_image implementation, child suppresses its own." That shape is correct and worth keeping — it is precisely what avoids duplicate symbols in the common case. What was wrong was the *condition* spvdb used to detect it. Being a subdirectory does not imply the parent's symbols are reachable. So the fix is at the producer of that decision: the parent now declares whether its copy is usable, via `SPVDB_PARENT_PROVIDES_STB_IMAGE`, and spvdb honors that declaration. `tools/CMakeLists.txt` sets it to `FALSE` for `SLANG_LIB_TYPE=STATIC` because that is exactly when Slang hides the symbols.

The alternative — dropping `STB_IMAGE_STATIC` from `cmake/CompilerFlags.cmake` — was rejected. That macro is there so a statically linked `libslang.a` does not export third-party `stbi_*` symbols into a consumer's link, which would collide with the consumer's own copy of stb. That is a deliberate property of a distributed static library, and spvdb (a test-only tool) should not weaken it.

Compiling a second copy in spvdb does not reintroduce the duplicate-symbol problem it was originally avoiding: in that configuration `slang-test-main.cpp`'s definitions are `static`, so they are invisible to the linker and cannot collide with spvdb's external ones. `slang-test-main.cpp` keeps calling its own internal copies; spvdb calls its own.

**Why the ASan build broke.** `spvdb` is created by a plain `add_library(spvdb STATIC ...)` at `tests/spvdb/CMakeLists.txt:124` and never passes through `set_default_compile_options`, which is where `SLANG_ENABLE_ASAN` turns into `/fsanitize=address`. `slang-test`, added via `slang_add_target` in `tools/CMakeLists.txt`, does get it — including on its precompiled header, which is why `cmake_pch.obj` is the object named in the diagnostic. MSVC records the container-annotation ABI in each object, the two disagree, and `link.exe` refuses with 12 `LNK2038` mismatches followed by `LNK1319`.

Here the offending shape is not an input to be handled but a target that was simply missing a required flag, so the fix is to supply it. Running the *whole* of `set_default_compile_options` on `spvdb` would be wrong — it would impose Slang's warning set and `-Werror`-style strictness on vendored third-party code that configures its own warnings at `tests/spvdb/CMakeLists.txt:149`. Copying the sanitizer flags into `tools/CMakeLists.txt` would be wrong too, since they would then drift from the canonical set. Extracting `add_sanitizer_options()` keeps one definition of the flags and lets a caller opt into just that concern. `set_default_compile_options` delegates to it, so existing targets — including those passing `SKIP_ASAN` — behave exactly as before; the function body is moved verbatim.

**Verification.** Configured and built `slang-test` from scratch with VS 2026 / Ninja Multi-Config in Debug. With `-DSLANG_LIB_TYPE=STATIC`, `slang-test.exe` links and `SPVDB_SKIP_STB_IMAGE_IMPL` is correctly absent from spvdb's objects. With `-DSLANG_ENABLE_ASAN=ON`, `slang-test.exe` links and spvdb's objects carry `/fsanitize=address`. In the default shared, non-ASan configuration `SPVDB_SKIP_STB_IMAGE_IMPL=1` is still set, confirming the common path is untouched.

This PR changes only the build system, so it carries no test of its own; the CMake Options workflow is the regression test, and both affected option builds are part of it.

### CODE REVIEW

**Comment by jkwak-work** [comment]
@coderabbitai review

**Comment by jkwak-work** [comment]
Closes https://github.com/shader-slang/slang/issues/13068
